apiVersion: v1
kind: Service
metadata:
  name: write-contact-api
spec:
  type: NodePort
  selector:
    app: write-contact-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
