apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-contact-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: read-contact-api
  template:
    metadata:
      labels:
        app: read-contact-api
    spec:
      containers:
        - name: read-contact-api
          image: mupedeal/contactregister-api-readcontact:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: contactregister-config
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: contactregister-secrets
                  key: ConnectionStrings__DefaultConnection
