FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y curl wget ca-certificates

RUN wget https://github.com/prometheus/prometheus/releases/download/v3.4.0/prometheus-3.4.0.linux-amd64.tar.gz && \
    tar xvf prometheus-3.4.0.linux-amd64.tar.gz && \
    mv prometheus-3.4.0.linux-amd64 /prometheus

WORKDIR /prometheus

EXPOSE 9090

CMD ["./prometheus", "--config.file=/etc/prometheus/prometheus.yml"]
