apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'contact-register-api-1'
        metrics_path: '/metrics'
        static_configs:
          - targets:
              - 'ddd-api:8080'
              - 'read-contact-api:8080'
              - 'write-contact-api:8080'
